name: Update All Maps

on:
  push:
    branches: [main]
    paths:
      - "convert_from_directories.py"
      - "convert_meta.py"
      - ".github/workflows/update-research-map.yml"
      - ".github/workflows/update-all-maps.yml"
  workflow_dispatch:

jobs:
  trigger-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read allowed maps
        id: read-maps
        run: |
          content=$(cat allowed_maps.json)
          echo "maps=$content" >> $GITHUB_OUTPUT

      - name: Trigger update workflows
        run: |
          maps=$(echo '${{ steps.read-maps.outputs.maps }}' | jq -r 'keys[]')
          for map in $maps; do
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.SOURCE_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/dispatches" \
              -d "{\"event_type\":\"update_research_map\",\"client_payload\":{\"map_repo\":\"$map\"}}"
            
            echo "Triggered update for $map"
            # Add a small delay to avoid rate limiting
            sleep 2
          done
